---
name: Chocolatey Package

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
on:    # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  CHOCO_PACKAGE_NAME: watlow-composer
  CHOCO_PUSH_URL: https://push.chocolatey.org/
  CHOCO_COMMUNITY_FEED: https://community.chocolatey.org/api/v2/

jobs:
  build_job:
    runs-on: windows-2016
    name: pack
    steps:
      -
        name: checkout
        uses: actions/checkout@v3
      -
        name: pack
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack
  test_job:
    runs-on: windows-2016
    name: test
    steps:
      -
        name: install
        run: |
          choco install -dv --source ".;${{ env.CHOCO_COMMUNITY_FEED }}" ${{ env.CHOCO_PACKAGE_NAME }}
  deploy_job:
    runs-on: windows-2016
    name: push
    steps:
      -
        name: set key
        run: |
          choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source ${{ env.CHOCO_PUSH_URL }}
      -
        name: push
        run: |
          choco push --api-key ${{ secrets.CHOCO_API_KEY }} --source ${{env.CHOCO_PUSH_URL }}
