---
name: Chocolatey Package

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
on:    # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CHOCO_PACKAGE_NAME: watlow-composer
  CHOCO_PUSH_URL: https://push.chocolatey.org/
  CHOCO_COMMUNITY_FEED: https://community.chocolatey.org/api/v2/

jobs:
  build_job:
    name: Pack
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: pack
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CHOCO_PACKAGE_NAME }}
          path: |
            *.nupkg
  test_job:
    name: test
    needs: build_job
    runs-on: windows-latest
    steps:
      - name: Download packagae
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CHOCO_PACKAGE_NAME }}
      - name: Install
        run: |
          choco install --source ".;${{ env.CHOCO_COMMUNITY_FEED }}" ${{ env.CHOCO_PACKAGE_NAME }}
      - name: Uninstall
        run: |
          choco uninstall ${{ env.CHOCO_PACKAGE_NAME }}
  deploy_job:
    name: Push
    needs: test_job
    runs-on: windows-latest
    steps:
      - name: Download packagae
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CHOCO_PACKAGE_NAME }}
      - name: Set key
        run: |
          choco apikey --key ${{ secrets.CHOCO_API_KEY }} --source ${{ env.CHOCO_PUSH_URL }}
      - name: Push
        run: |
          choco push --api-key ${{ secrets.CHOCO_API_KEY }} --source ${{env.CHOCO_PUSH_URL }}
